name: Build
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Build pages
      env:
        NODE_ENV: production
      run: yarn run export

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-site
        path: ./out
